# Generated by Django 3.1.12 on 2024-12-21 22:55

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('current_price', models.FloatField()),
                ('desired_price', models.FloatField()),
                ('price_history', djongo.models.fields.JSONField(default=list)),
            ],
        ),
    ]
