# Generated by Django 3.1.12 on 2024-12-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='user_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
