# Generated by Django 3.1.12 on 2024-12-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20241222_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_notified_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
