# Generated by Django 3.1.12 on 2024-12-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_product_last_notified_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
