# Generated by Django 3.1.12 on 2024-12-25 02:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_apiusage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiusage',
            old_name='request_count',
            new_name='total_requests',
        ),
        migrations.RemoveField(
            model_name='apiusage',
            name='reset_date',
        ),
        migrations.AddField(
            model_name='apiusage',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
